public class LearningConstants {
    
    // Email Templates
    public static final String ASSIGNMENT_NOTIFICATION_EMAIL = 'Assignment_Notification_Email';
    
    // Notification Types
    public static final String ASSIGNMENT_NOTIFICATION = 'Assignment_Notification';
    
    // Permission Set Names
    public static final String COURSE_ADMIN_PERMISSION_SET = 'Course_Admin';
    public static final String COURSE_USER_PERMISSION_SET = 'Course_User';
}
